from io import BytesIO
from pathlib import Path

import joblib
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak,
)


# ============================================================
# CONFIGURATION
# ============================================================

BASE_DIR = Path(__file__).resolve().parent


# ============================================================
# SAFE VALUE FORMATTERS
# ============================================================

def safe_float(value, default=0.0):
    try:
        return float(value)
    except Exception:
        return default


def format_number(value, decimals=0):
    try:
        return f"{float(value):,.{decimals}f}"
    except Exception:
        return str(value)


def format_currency(value):
    try:
        return f"{float(value):,.2f}"
    except Exception:
        return str(value)


def escape_text(value):
    """
    Safely convert text to something ReportLab can render.
    """
    if value is None:
        return ""

    text = str(value)

    replacements = {
        "&": "&amp;",
        "<": "&lt;",
        ">": "&gt;",
    }

    for old, new in replacements.items():
        text = text.replace(old, new)

    return text


# ============================================================
# LOAD MODEL METRICS
# ============================================================

def load_metrics():

    metrics_path = BASE_DIR / "model_metrics.joblib"

    if not metrics_path.exists():
        return {}

    try:
        metrics = joblib.load(metrics_path)

        if isinstance(metrics, dict):
            return metrics

    except Exception:
        pass

    return {}


# ============================================================
# PAGE HEADER / FOOTER
# ============================================================

def add_page_decorations(canvas, doc):

    canvas.saveState()

    width, height = A4

    # Header
    canvas.setFillColor(colors.HexColor("#111827"))

    canvas.rect(
        0,
        height - 18 * mm,
        width,
        18 * mm,
        fill=1,
        stroke=0,
    )

    canvas.setFillColor(colors.white)

    canvas.setFont("Helvetica-Bold", 13)

    canvas.drawString(
        18 * mm,
        height - 11 * mm,
        "CrediX",
    )

    canvas.setFont("Helvetica", 8)

    canvas.drawRightString(
        width - 18 * mm,
        height - 11 * mm,
        "Explainable Machine Learning Credit Intelligence",
    )

    # Footer
    canvas.setStrokeColor(colors.HexColor("#D1D5DB"))

    canvas.line(
        18 * mm,
        14 * mm,
        width - 18 * mm,
        14 * mm,
    )

    canvas.setFillColor(colors.HexColor("#6B7280"))

    canvas.setFont("Helvetica", 7)

    canvas.drawString(
        18 * mm,
        8 * mm,
        "CrediX — Analytical and educational decision-support system",
    )

    canvas.drawRightString(
        width - 18 * mm,
        8 * mm,
        f"Page {doc.page}",
    )

    canvas.restoreState()


# ============================================================
# MAIN PDF GENERATOR
# ============================================================

def generate_pdf(
    input_df,
    prediction,
    probabilities,
    recommendations,
):
    """
    Generate the CrediX customer credit assessment PDF.

    Parameters
    ----------
    input_df : pandas.DataFrame
        Customer financial profile.

    prediction : str
        Predicted credit category.

    probabilities : array-like
        Model probabilities for each credit category.

    recommendations : list
        Personalised recommendations generated by app.py.

    Returns
    -------
    bytes
        Generated PDF bytes.
    """

    buffer = BytesIO()

    # ========================================================
    # DOCUMENT
    # ========================================================

    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=18 * mm,
        leftMargin=18 * mm,
        topMargin=25 * mm,
        bottomMargin=20 * mm,
        title="CrediX Credit Intelligence Report",
        author="CrediX",
    )

    # ========================================================
    # STYLES
    # ========================================================

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "CrediXTitle",
        parent=styles["Title"],
        fontName="Helvetica-Bold",
        fontSize=24,
        leading=29,
        textColor=colors.HexColor("#111827"),
        alignment=TA_LEFT,
        spaceAfter=6,
    )

    subtitle_style = ParagraphStyle(
        "CrediXSubtitle",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=10,
        leading=15,
        textColor=colors.HexColor("#6B7280"),
        spaceAfter=18,
    )

    section_style = ParagraphStyle(
        "Section",
        parent=styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=14,
        leading=18,
        textColor=colors.HexColor("#111827"),
        spaceBefore=14,
        spaceAfter=8,
    )

    normal_style = ParagraphStyle(
        "NormalCustom",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=9,
        leading=14,
        textColor=colors.HexColor("#374151"),
        spaceAfter=5,
    )

    small_style = ParagraphStyle(
        "Small",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=8,
        leading=12,
        textColor=colors.HexColor("#6B7280"),
    )

    result_style = ParagraphStyle(
        "Result",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=22,
        leading=27,
        textColor=colors.HexColor("#111827"),
        alignment=TA_CENTER,
    )

    # ========================================================
    # CONTENT
    # ========================================================

    story = []

    # ========================================================
    # TITLE
    # ========================================================

    story.append(
        Paragraph(
            "CrediX Credit Intelligence Report",
            title_style,
        )
    )

    story.append(
        Paragraph(
            "Explainable Machine Learning based credit assessment",
            subtitle_style,
        )
    )

    # ========================================================
    # PREDICTION SUMMARY
    # ========================================================

    story.append(
        Paragraph(
            "Credit Assessment",
            section_style,
        )
    )

    prediction_text = escape_text(prediction)

    try:
        probabilities_list = list(probabilities)
    except Exception:
        probabilities_list = []

    confidence = 0.0

    if probabilities_list:
        try:
            confidence = max(
                safe_float(x)
                for x in probabilities_list
            ) * 100
        except Exception:
            confidence = 0.0

    result_data = [
        [
            Paragraph(
                "<b>Predicted Credit Category</b>",
                normal_style,
            ),
            Paragraph(
                "<b>Model Confidence</b>",
                normal_style,
            ),
        ],
        [
            Paragraph(
                prediction_text,
                result_style,
            ),
            Paragraph(
                f"{confidence:.2f}%",
                result_style,
            ),
        ],
    ]

    result_table = Table(
        result_data,
        colWidths=[82 * mm, 82 * mm],
    )

    result_table.setStyle(
        TableStyle(
            [
                (
                    "BACKGROUND",
                    (0, 0),
                    (-1, -1),
                    colors.HexColor("#F3F4F6"),
                ),
                (
                    "BOX",
                    (0, 0),
                    (-1, -1),
                    0.8,
                    colors.HexColor("#D1D5DB"),
                ),
                (
                    "INNERGRID",
                    (0, 0),
                    (-1, -1),
                    0.5,
                    colors.HexColor("#E5E7EB"),
                ),
                (
                    "VALIGN",
                    (0, 0),
                    (-1, -1),
                    "MIDDLE",
                ),
                (
                    "ALIGN",
                    (0, 0),
                    (-1, -1),
                    "CENTER",
                ),
                (
                    "TOPPADDING",
                    (0, 0),
                    (-1, -1),
                    10,
                ),
                (
                    "BOTTOMPADDING",
                    (0, 0),
                    (-1, -1),
                    10,
                ),
            ]
        )
    )

    story.append(result_table)

    story.append(Spacer(1, 10))

    story.append(
        Paragraph(
            "The prediction is generated using the trained CrediX "
            "Random Forest classification pipeline.",
            normal_style,
        )
    )

    # ========================================================
    # FINANCIAL PROFILE
    # ========================================================

    story.append(
        Paragraph(
            "Customer Financial Profile",
            section_style,
        )
    )

    profile_labels = {
        "Age": "Age",
        "Occupation": "Occupation",
        "Annual_Income": "Annual Income",
        "Num_Bank_Accounts": "Bank Accounts",
        "Num_Credit_Card": "Credit Cards",
        "Interest_Rate": "Interest Rate",
        "Num_of_Loan": "Number of Loans",
        "Delay_from_due_date": "Delay From Due Date",
        "Num_of_Delayed_Payment": "Delayed Payments",
        "Changed_Credit_Limit": "Changed Credit Limit",
        "Num_Credit_Inquiries": "Credit Inquiries",
        "Credit_Mix": "Credit Mix",
        "Outstanding_Debt": "Outstanding Debt",
        "Credit_Utilization_Ratio": "Credit Utilization Ratio",
        "Payment_of_Min_Amount": "Minimum Payment Behaviour",
        "Total_EMI_per_month": "Monthly EMI",
        "Amount_invested_monthly": "Monthly Investment",
        "Payment_Behaviour": "Payment Behaviour",
        "Monthly_Balance": "Monthly Balance",
        "Credit_History_Age_Months": "Credit History Age",
    }

    profile_rows = []

    if input_df is not None and len(input_df) > 0:

        row = input_df.iloc[0]

        for column in input_df.columns:

            label = profile_labels.get(
                column,
                column.replace("_", " "),
            )

            value = row[column]

            if isinstance(value, (int, float)):

                if "Income" in label or \
                   "Debt" in label or \
                   "Balance" in label or \
                   "EMI" in label or \
                   "Investment" in label:

                    display_value = format_number(
                        value,
                        2,
                    )

                else:

                    display_value = format_number(
                        value,
                        2,
                    )

            else:

                display_value = str(value)

            profile_rows.append(
                [
                    Paragraph(
                        escape_text(label),
                        normal_style,
                    ),
                    Paragraph(
                        escape_text(display_value),
                        normal_style,
                    ),
                ]
            )

    if profile_rows:

        profile_table = Table(
            profile_rows,
            colWidths=[
                80 * mm,
                84 * mm,
            ],
        )

        profile_table.setStyle(
            TableStyle(
                [
                    (
                        "BACKGROUND",
                        (0, 0),
                        (0, -1),
                        colors.HexColor("#F9FAFB"),
                    ),
                    (
                        "BOX",
                        (0, 0),
                        (-1, -1),
                        0.7,
                        colors.HexColor("#D1D5DB"),
                    ),
                    (
                        "INNERGRID",
                        (0, 0),
                        (-1, -1),
                        0.4,
                        colors.HexColor("#E5E7EB"),
                    ),
                    (
                        "VALIGN",
                        (0, 0),
                        (-1, -1),
                        "MIDDLE",
                    ),
                    (
                        "LEFTPADDING",
                        (0, 0),
                        (-1, -1),
                        7,
                    ),
                    (
                        "RIGHTPADDING",
                        (0, 0),
                        (-1, -1),
                        7,
                    ),
                ]
            )
        )

        story.append(profile_table)

    # ========================================================
    # PREDICTION PROBABILITIES
    # ========================================================

    story.append(
        Paragraph(
            "Prediction Probability",
            section_style,
        )
    )

    probability_rows = [
        [
            Paragraph(
                "<b>Credit Category</b>",
                normal_style,
            ),
            Paragraph(
                "<b>Probability</b>",
                normal_style,
            ),
        ]
    ]

    class_names = [
        "Good",
        "Poor",
        "Standard",
    ]

    for i, probability in enumerate(
        probabilities_list
    ):

        if i < len(class_names):
            class_name = class_names[i]
        else:
            class_name = f"Class {i + 1}"

        probability_rows.append(
            [
                Paragraph(
                    escape_text(class_name),
                    normal_style,
                ),
                Paragraph(
                    f"{safe_float(probability) * 100:.2f}%",
                    normal_style,
                ),
            ]
        )

    probability_table = Table(
        probability_rows,
        colWidths=[
            100 * mm,
            64 * mm,
        ],
    )

    probability_table.setStyle(
        TableStyle(
            [
                (
                    "BACKGROUND",
                    (0, 0),
                    (-1, 0),
                    colors.HexColor("#111827"),
                ),
                (
                    "TEXTCOLOR",
                    (0, 0),
                    (-1, 0),
                    colors.white,
                ),
                (
                    "BOX",
                    (0, 0),
                    (-1, -1),
                    0.7,
                    colors.HexColor("#D1D5DB"),
                ),
                (
                    "INNERGRID",
                    (0, 0),
                    (-1, -1),
                    0.4,
                    colors.HexColor("#E5E7EB"),
                ),
                (
                    "ALIGN",
                    (1, 1),
                    (1, -1),
                    "RIGHT",
                ),
                (
                    "BACKGROUND",
                    (0, 1),
                    (-1, -1),
                    colors.HexColor("#F9FAFB"),
                ),
                (
                    "TOPPADDING",
                    (0, 0),
                    (-1, -1),
                    7,
                ),
                (
                    "BOTTOMPADDING",
                    (0, 0),
                    (-1, -1),
                    7,
                ),
            ]
        )
    )

    story.append(probability_table)

    # ========================================================
    # MODEL PERFORMANCE
    # ========================================================

    metrics = load_metrics()

    story.append(
        Paragraph(
            "Machine Learning Model Performance",
            section_style,
        )
    )

    story.append(
        Paragraph(
            "Final model: Random Forest Classifier",
            normal_style,
        )
    )

    metric_rows = [
        [
            Paragraph("<b>Metric</b>", normal_style),
            Paragraph("<b>Result</b>", normal_style),
        ]
    ]

    metric_mapping = [
        ("accuracy", "Accuracy"),
        ("precision", "Precision"),
        ("recall", "Recall"),
        ("f1", "F1-Score"),
    ]

    for key, label in metric_mapping:

        value = metrics.get(key)

        if value is not None:

            try:
                display_value = f"{float(value) * 100:.2f}%"
            except Exception:
                display_value = str(value)

            metric_rows.append(
                [
                    Paragraph(
                        label,
                        normal_style,
                    ),
                    Paragraph(
                        display_value,
                        normal_style,
                    ),
                ]
            )

    if len(metric_rows) == 1:

        metric_rows.extend(
            [
                [
                    Paragraph(
                        "Accuracy",
                        normal_style,
                    ),
                    Paragraph(
                        "80.20%",
                        normal_style,
                    ),
                ],
                [
                    Paragraph(
                        "Precision",
                        normal_style,
                    ),
                    Paragraph(
                        "79.86%",
                        normal_style,
                    ),
                ],
                [
                    Paragraph(
                        "Recall",
                        normal_style,
                    ),
                    Paragraph(
                        "80.20%",
                        normal_style,
                    ),
                ],
                [
                    Paragraph(
                        "F1-Score",
                        normal_style,
                    ),
                    Paragraph(
                        "79.65%",
                        normal_style,
                    ),
                ],
            ]
        )

    metrics_table = Table(
        metric_rows,
        colWidths=[
            100 * mm,
            64 * mm,
        ],
    )

    metrics_table.setStyle(
        TableStyle(
            [
                (
                    "BACKGROUND",
                    (0, 0),
                    (-1, 0),
                    colors.HexColor("#111827"),
                ),
                (
                    "TEXTCOLOR",
                    (0, 0),
                    (-1, 0),
                    colors.white,
                ),
                (
                    "BOX",
                    (0, 0),
                    (-1, -1),
                    0.7,
                    colors.HexColor("#D1D5DB"),
                ),
                (
                    "INNERGRID",
                    (0, 0),
                    (-1, -1),
                    0.4,
                    colors.HexColor("#E5E7EB"),
                ),
                (
                    "BACKGROUND",
                    (0, 1),
                    (-1, -1),
                    colors.HexColor("#F9FAFB"),
                ),
                (
                    "ALIGN",
                    (1, 1),
                    (1, -1),
                    "RIGHT",
                ),
                (
                    "TOPPADDING",
                    (0, 0),
                    (-1, -1),
                    7,
                ),
                (
                    "BOTTOMPADDING",
                    (0, 0),
                    (-1, -1),
                    7,
                ),
            ]
        )
    )

    story.append(metrics_table)

    # ========================================================
    # RECOMMENDATIONS
    # ========================================================

    story.append(
        Paragraph(
            "Personalised Recommendations",
            section_style,
        )
    )

    if recommendations:

        for recommendation in recommendations:

            try:

                title, text = recommendation

                story.append(
                    Paragraph(
                        f"<b>{escape_text(title)}</b>",
                        normal_style,
                    )
                )

                story.append(
                    Paragraph(
                        escape_text(text),
                        normal_style,
                    )
                )

                story.append(
                    Spacer(1, 6)
                )

            except Exception:

                story.append(
                    Paragraph(
                        escape_text(
                            recommendation
                        ),
                        normal_style,
                    )
                )

    else:

        story.append(
            Paragraph(
                "No specific warning indicators were identified "
                "from the current financial profile.",
                normal_style,
            )
        )

    # ========================================================
    # METHODOLOGY
    # ========================================================

    story.append(
        Paragraph(
            "Machine Learning Methodology",
            section_style,
        )
    )

    methodology_text = (
        "CrediX uses a supervised machine learning pipeline for "
        "multi-class credit classification. The system processes "
        "numerical and categorical financial attributes before "
        "passing the transformed data to a Random Forest classifier. "
        "The model was evaluated using held-out test data and "
        "cross-validation. Explainable AI functionality is provided "
        "through SHAP-based feature analysis."
    )

    story.append(
        Paragraph(
            methodology_text,
            normal_style,
        )
    )

    # ========================================================
    # DISCLAIMER
    # ========================================================

    story.append(
        Spacer(1, 12)
    )

    disclaimer_data = [
        [
            Paragraph(
                "<b>Important Notice</b><br/>"
                "CrediX is an analytical and educational "
                "decision-support system. Machine learning "
                "predictions are estimates and should not be "
                "treated as financial advice, a lending decision, "
                "or a guarantee of credit approval.",
                small_style,
            )
        ]
    ]

    disclaimer_table = Table(
        disclaimer_data,
        colWidths=[164 * mm],
    )

    disclaimer_table.setStyle(
        TableStyle(
            [
                (
                    "BACKGROUND",
                    (0, 0),
                    (-1, -1),
                    colors.HexColor("#F3F4F6"),
                ),
                (
                    "BOX",
                    (0, 0),
                    (-1, -1),
                    0.7,
                    colors.HexColor("#D1D5DB"),
                ),
                (
                    "LEFTPADDING",
                    (0, 0),
                    (-1, -1),
                    10,
                ),
                (
                    "RIGHTPADDING",
                    (0, 0),
                    (-1, -1),
                    10,
                ),
                (
                    "TOPPADDING",
                    (0, 0),
                    (-1, -1),
                    10,
                ),
                (
                    "BOTTOMPADDING",
                    (0, 0),
                    (-1, -1),
                    10,
                ),
            ]
        )
    )

    story.append(disclaimer_table)

    # ========================================================
    # BUILD PDF
    # ========================================================

    doc.build(
        story,
        onFirstPage=add_page_decorations,
        onLaterPages=add_page_decorations,
    )

    buffer.seek(0)

    return buffer.getvalue()


# ============================================================
# DIRECT TEST
# ============================================================

if __name__ == "__main__":

    import pandas as pd

    sample_customer = pd.DataFrame(
        [
            {
                "Age": 30,
                "Occupation": "Engineer",
                "Annual_Income": 60000,
                "Num_Bank_Accounts": 3,
                "Num_Credit_Card": 4,
                "Interest_Rate": 8,
                "Num_of_Loan": 2,
                "Delay_from_due_date": 5,
                "Num_of_Delayed_Payment": 1,
                "Changed_Credit_Limit": 10.0,
                "Num_Credit_Inquiries": 2,
                "Credit_Mix": "Good",
                "Outstanding_Debt": 15000,
                "Credit_Utilization_Ratio": 25.0,
                "Payment_of_Min_Amount": "Yes",
                "Total_EMI_per_month": 5000,
                "Amount_invested_monthly": 3000,
                "Payment_Behaviour": "High_spent_Medium_value_payments",
                "Monthly_Balance": 40000,
                "Credit_History_Age_Months": 120,
            }
        ]
    )

    sample_probabilities = [
        0.288,
        0.212,
        0.500,
    ]

    sample_recommendations = [
        (
            "Manage outstanding debt",
            "Consider reducing high-cost outstanding debt "
            "to strengthen your overall financial profile.",
        ),
        (
            "Maintain healthy payment behaviour",
            "Continue making payments on time and avoid "
            "unnecessary additional borrowing.",
        ),
    ]

    pdf_bytes = generate_pdf(
        sample_customer,
        "Standard",
        sample_probabilities,
        sample_recommendations,
    )

    output_path = BASE_DIR / "CrediX_Test_Report.pdf"

    with open(
        output_path,
        "wb",
    ) as file:
        file.write(pdf_bytes)

    print(
        f"PDF successfully generated: {output_path}"
    )